//! Shared NVS-backed key/value storage, on the "nvs" flash partition.
//!
//! One instance for the whole firmware: `esp-nvs`'s `Nvs` keeps in-RAM page
//! state mirroring the flash partition, so two independent instances
//! pointed at the same partition (one per feature that wants to persist
//! something) would each have a stale view of the other's writes.

use alloc::string::String;

use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::mutex::Mutex;
use esp_hal::peripherals::FLASH;
use esp_nvs::error::Error as NvsError;
use esp_nvs::{Get, Key, Nvs, Set};
use esp_storage::FlashStorage;
use log::warn;

/// `Storage` shared between tasks (the Improv/Wi-Fi task and the HTTP config
/// server both need it). Lock only around the actual get/set call, not
/// around unrelated work, so one task blocking on Wi-Fi doesn't stall the
/// other's access to flash.
pub type SharedStorage = Mutex<CriticalSectionRawMutex, Storage>;

/// Offset and size of the "nvs" partition in the default partition table
/// generated by `esp-bootloader-esp-idf` (confirmed at every boot: `nvs
/// WiFi data 01 02 00009000 00006000`). Update these if a custom partition
/// table changes them.
const PARTITION_OFFSET: usize = 0x9000;
const PARTITION_SIZE: usize = 0x6000;

const HW_NAMESPACE: Key = Key::from_str("hw");
const KEY_LED_GPIO: Key = Key::from_str("led_gpio");

const SYSTEM_NAMESPACE: Key = Key::from_str("system");
const KEY_LOCKED: Key = Key::from_str("locked");

pub struct Storage {
    /// `None` if the partition couldn't be opened (logged when that
    /// happens); reads then return `None` and writes are silently dropped,
    /// same as an empty/never-written store.
    nvs: Option<Nvs<FlashStorage<'static>>>,
}

impl Storage {
    pub fn new(flash: FLASH<'static>) -> Self {
        let nvs = match Nvs::new(PARTITION_OFFSET, PARTITION_SIZE, FlashStorage::new(flash)) {
            Ok(nvs) => Some(nvs),
            Err(e) => {
                warn!("NVS unavailable, nothing will persist across reboots: {e:?}");
                None
            }
        };
        Self { nvs }
    }

    pub fn get_string(&mut self, namespace: &Key, key: &Key) -> Option<String> {
        self.get(namespace, key)
    }

    pub fn set_string(&mut self, namespace: &Key, key: &Key, value: &str) {
        self.set(namespace, key, value);
    }

    pub fn get_u8(&mut self, namespace: &Key, key: &Key) -> Option<u8> {
        self.get(namespace, key)
    }

    pub fn set_u8(&mut self, namespace: &Key, key: &Key, value: u8) {
        self.set(namespace, key, value);
    }

    pub fn get_bool(&mut self, namespace: &Key, key: &Key) -> Option<bool> {
        self.get(namespace, key)
    }

    pub fn set_bool(&mut self, namespace: &Key, key: &Key, value: bool) {
        self.set(namespace, key, value);
    }

    /// Whether the HTTP hardware-config page (`src/http/`) has been
    /// locked. Once set, only a full flash erase (which wipes this whole
    /// NVS partition, Wi-Fi credentials included -- the "Erase" option in
    /// ESP Web Tools, same one-way reset ESPHome devices use) clears it.
    pub fn is_locked(&mut self) -> bool {
        self.get_bool(&SYSTEM_NAMESPACE, &KEY_LOCKED)
            .unwrap_or(false)
    }

    pub fn lock(&mut self) {
        self.set_bool(&SYSTEM_NAMESPACE, &KEY_LOCKED, true);
    }

    /// `None` if no status LED is configured.
    pub fn load_led_gpio(&mut self) -> Option<u8> {
        self.get_u8(&HW_NAMESPACE, &KEY_LED_GPIO)
    }

    pub fn save_led_gpio(&mut self, gpio: Option<u8>) {
        match gpio {
            Some(gpio) => self.set_u8(&HW_NAMESPACE, &KEY_LED_GPIO, gpio),
            None => self.delete(&HW_NAMESPACE, &KEY_LED_GPIO),
        }
    }

    pub fn delete(&mut self, namespace: &Key, key: &Key) {
        let Some(nvs) = self.nvs.as_mut() else {
            return;
        };
        match nvs.delete(namespace, key) {
            Ok(()) | Err(NvsError::NamespaceNotFound | NvsError::KeyNotFound) => {}
            Err(e) => warn!("Failed to delete {}: {e:?}", key.as_str()),
        }
    }

    fn get<T>(&mut self, namespace: &Key, key: &Key) -> Option<T>
    where
        Nvs<FlashStorage<'static>>: Get<T>,
    {
        let nvs = self.nvs.as_mut()?;
        match nvs.get(namespace, key) {
            Ok(value) => Some(value),
            Err(NvsError::NamespaceNotFound | NvsError::KeyNotFound) => None,
            Err(e) => {
                warn!("Failed to read {}: {e:?}", key.as_str());
                None
            }
        }
    }

    fn set<T>(&mut self, namespace: &Key, key: &Key, value: T)
    where
        Nvs<FlashStorage<'static>>: Set<T>,
    {
        let Some(nvs) = self.nvs.as_mut() else {
            return;
        };
        if let Err(e) = nvs.set(namespace, key, value) {
            warn!("Failed to save {}: {e:?}", key.as_str());
        }
    }
}
