//! Shared NVS-backed key/value storage, on the "nvs" flash partition.
//!
//! One instance for the whole firmware: `esp-nvs`'s `Nvs` keeps in-RAM page
//! state mirroring the flash partition, so two independent instances
//! pointed at the same partition (one per feature that wants to persist
//! something) would each have a stale view of the other's writes.

use alloc::collections::BTreeMap;
use alloc::string::String;
use alloc::vec::Vec;

use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::mutex::Mutex;
use esp_hal::peripherals::FLASH;
use esp_nvs::error::Error as NvsError;
use esp_nvs::{Get, Key, Nvs, Set};
use esp_storage::FlashStorage;
use log::warn;

/// `Storage` shared between tasks (the Improv/Wi-Fi task and the HTTP config
/// server both need it). Lock only around the actual get/set call, not
/// around unrelated work, so one task blocking on Wi-Fi doesn't stall the
/// other's access to flash.
pub type SharedStorage = Mutex<CriticalSectionRawMutex, Storage>;

/// Offset and size of the "nvs" partition in the default partition table
/// generated by `esp-bootloader-esp-idf` (confirmed at every boot: `nvs
/// WiFi data 01 02 00009000 00006000`). Update these if a custom partition
/// table changes them.
const PARTITION_OFFSET: usize = 0x9000;
const PARTITION_SIZE: usize = 0x6000;

const HW_NAMESPACE: Key = Key::from_str("hw");
const KEY_LED_GPIO: Key = Key::from_str("led_gpio");

const SYSTEM_NAMESPACE: Key = Key::from_str("system");
const KEY_LOCKED: Key = Key::from_str("locked");
const KEY_APP_PORT: Key = Key::from_str("app_port");

/// McuConfigMap (contrat §4a/§7a): arbitrary admin-defined key/value pairs,
/// opaque to the agent. Internal keys here are prefixed `_` (currently just
/// the generation counter), excluded from what admins can write or see
/// dumped back -- same convention the C reference uses.
const CFG_NAMESPACE: Key = Key::from_str("cfg");
const KEY_CFG_GENERATION: Key = Key::from_str("_gen");
/// NVS keys are capped at 15 bytes (`esp_nvs::MAX_KEY_LENGTH`); admin-
/// supplied config keys need checking against that *before* `Key::from_str`,
/// which panics past it rather than erroring.
const MAX_CFG_KEY_LEN: usize = 15;

pub struct Storage {
    /// `None` if the partition couldn't be opened (logged when that
    /// happens); reads then return `None` and writes are silently dropped,
    /// same as an empty/never-written store.
    nvs: Option<Nvs<FlashStorage<'static>>>,
    /// McuConfigMap snapshot taken once, right here at construction (which
    /// only ever happens once, at boot) -- contrat §4a: "L'agent lit la
    /// config NVS une seule fois au boot." Stays frozen even if `POST
    /// /config` changes the live NVS values afterward; `GET /config`
    /// reports both, so the Core can tell "saved" apart from "active".
    active_cfg: BTreeMap<String, String>,
    active_cfg_generation: u32,
}

impl Storage {
    pub fn new(flash: FLASH<'static>) -> Self {
        let nvs = match Nvs::new(PARTITION_OFFSET, PARTITION_SIZE, FlashStorage::new(flash)) {
            Ok(nvs) => Some(nvs),
            Err(e) => {
                warn!("NVS unavailable, nothing will persist across reboots: {e:?}");
                None
            }
        };
        let mut storage = Self { nvs, active_cfg: BTreeMap::new(), active_cfg_generation: 0 };
        storage.active_cfg_generation = storage.cfg_generation();
        storage.active_cfg = storage.cfg_entries();
        storage
    }

    pub fn get_string(&mut self, namespace: &Key, key: &Key) -> Option<String> {
        self.get(namespace, key)
    }

    pub fn set_string(&mut self, namespace: &Key, key: &Key, value: &str) {
        self.set(namespace, key, value);
    }

    pub fn get_u8(&mut self, namespace: &Key, key: &Key) -> Option<u8> {
        self.get(namespace, key)
    }

    pub fn set_u8(&mut self, namespace: &Key, key: &Key, value: u8) {
        self.set(namespace, key, value);
    }

    pub fn get_bool(&mut self, namespace: &Key, key: &Key) -> Option<bool> {
        self.get(namespace, key)
    }

    pub fn set_bool(&mut self, namespace: &Key, key: &Key, value: bool) {
        self.set(namespace, key, value);
    }

    pub fn get_u16(&mut self, namespace: &Key, key: &Key) -> Option<u16> {
        self.get(namespace, key)
    }

    pub fn set_u16(&mut self, namespace: &Key, key: &Key, value: u16) {
        self.set(namespace, key, value);
    }

    pub fn get_u32(&mut self, namespace: &Key, key: &Key) -> Option<u32> {
        self.get(namespace, key)
    }

    pub fn set_u32(&mut self, namespace: &Key, key: &Key, value: u32) {
        self.set(namespace, key, value);
    }

    /// Whether the HTTP hardware-config page (`src/http/`) has been
    /// locked. Once set, only a full flash erase (which wipes this whole
    /// NVS partition, Wi-Fi credentials included -- the "Erase" option in
    /// ESP Web Tools, same one-way reset ESPHome devices use) clears it.
    pub fn is_locked(&mut self) -> bool {
        self.get_bool(&SYSTEM_NAMESPACE, &KEY_LOCKED)
            .unwrap_or(false)
    }

    pub fn lock(&mut self) {
        self.set_bool(&SYSTEM_NAMESPACE, &KEY_LOCKED, true);
    }

    /// Round-trips a canary value through NVS (write, read back, erase).
    /// Used by `GET /v1alpha1/health`'s `storage` check (contrat §4): all
    /// the agent's critical state (staged OTA, token, config) lives in
    /// NVS, so if it's corrupted or full the device should say so, not
    /// silently claim to be healthy.
    pub fn self_check(&mut self) -> bool {
        const CANARY: Key = Key::from_str("canary");
        const VALUE: u8 = 0xA5;
        self.set_u8(&SYSTEM_NAMESPACE, &CANARY, VALUE);
        let ok = self.get_u8(&SYSTEM_NAMESPACE, &CANARY) == Some(VALUE);
        self.delete(&SYSTEM_NAMESPACE, &CANARY);
        ok
    }

    /// `None` if no status LED is configured.
    pub fn load_led_gpio(&mut self) -> Option<u8> {
        self.get_u8(&HW_NAMESPACE, &KEY_LED_GPIO)
    }

    pub fn save_led_gpio(&mut self, gpio: Option<u8>) {
        match gpio {
            Some(gpio) => self.set_u8(&HW_NAMESPACE, &KEY_LED_GPIO, gpio),
            None => self.delete(&HW_NAMESPACE, &KEY_LED_GPIO),
        }
    }

    /// The app service's TCP port (contrat §4, `POST /app/port`). `80` if
    /// never set -- matches what this agent has always bound to, since
    /// there's no separate workload process here for the default to differ
    /// from (see `agent.rs`'s doc comment on `Info::app_port`).
    pub fn load_app_port(&mut self) -> u16 {
        self.get_u16(&SYSTEM_NAMESPACE, &KEY_APP_PORT).unwrap_or(80)
    }

    pub fn save_app_port(&mut self, port: u16) {
        self.set_u16(&SYSTEM_NAMESPACE, &KEY_APP_PORT, port);
    }

    /// Current McuConfigMap generation in NVS (contrat §4a) -- distinct
    /// from `active_cfg_generation()`, which is what this boot actually
    /// loaded and stays fixed until the next reboot.
    pub fn cfg_generation(&mut self) -> u32 {
        self.get_u32(&CFG_NAMESPACE, &KEY_CFG_GENERATION).unwrap_or(0)
    }

    pub fn active_cfg_generation(&self) -> u32 {
        self.active_cfg_generation
    }

    pub fn active_cfg(&self) -> &BTreeMap<String, String> {
        &self.active_cfg
    }

    /// Sets one McuConfigMap key (contrat §4a). An empty `value` erases the
    /// key (reset to the build default) -- the empty string is otherwise
    /// reserved, never a legitimate stored value. Rejects keys that can't
    /// exist here at all (empty, too long for NVS, or `_`-prefixed/internal)
    /// by silently doing nothing, rather than risking a panic from
    /// `Key::from_str` on an oversized admin-supplied key. Doesn't bump the
    /// generation -- call [`Self::cfg_bump_generation`] once after a batch.
    pub fn cfg_set(&mut self, key: &str, value: &str) {
        if key.is_empty() || key.len() > MAX_CFG_KEY_LEN || key.starts_with('_') {
            return;
        }
        let key = Key::from_str(key);
        if value.is_empty() {
            self.delete(&CFG_NAMESPACE, &key);
        } else {
            self.set_string(&CFG_NAMESPACE, &key, value);
        }
    }

    pub fn cfg_bump_generation(&mut self) -> u32 {
        let next = self.cfg_generation().wrapping_add(1);
        self.set_u32(&CFG_NAMESPACE, &KEY_CFG_GENERATION, next);
        next
    }

    /// Every user-defined McuConfigMap key currently in NVS (namespace
    /// `"cfg"`), excluding the internal `_gen` counter. `nvs.keys()`
    /// borrows the whole `Nvs` for its iterator's lifetime, so results are
    /// collected into an owned `Vec` first -- otherwise the per-key
    /// `nvs.get()` calls below couldn't borrow it again to read values.
    pub fn cfg_entries(&mut self) -> BTreeMap<String, String> {
        let mut out = BTreeMap::new();
        let Some(nvs) = self.nvs.as_mut() else {
            return out;
        };
        let keys: Vec<(Key, Key)> = nvs.keys().filter_map(Result::ok).collect();
        for (namespace, key) in keys {
            if namespace.as_str() != CFG_NAMESPACE.as_str() || key.as_str().starts_with('_') {
                continue;
            }
            if let Ok(value) = nvs.get::<String>(&namespace, &key) {
                out.insert(String::from(key.as_str()), value);
            }
        }
        out
    }

    pub fn delete(&mut self, namespace: &Key, key: &Key) {
        let Some(nvs) = self.nvs.as_mut() else {
            return;
        };
        match nvs.delete(namespace, key) {
            Ok(()) | Err(NvsError::NamespaceNotFound | NvsError::KeyNotFound) => {}
            Err(e) => warn!("Failed to delete {}: {e:?}", key.as_str()),
        }
    }

    fn get<T>(&mut self, namespace: &Key, key: &Key) -> Option<T>
    where
        Nvs<FlashStorage<'static>>: Get<T>,
    {
        let nvs = self.nvs.as_mut()?;
        match nvs.get(namespace, key) {
            Ok(value) => Some(value),
            Err(NvsError::NamespaceNotFound | NvsError::KeyNotFound) => None,
            Err(e) => {
                warn!("Failed to read {}: {e:?}", key.as_str());
                None
            }
        }
    }

    fn set<T>(&mut self, namespace: &Key, key: &Key, value: T)
    where
        Nvs<FlashStorage<'static>>: Set<T>,
    {
        let Some(nvs) = self.nvs.as_mut() else {
            return;
        };
        if let Err(e) = nvs.set(namespace, key, value) {
            warn!("Failed to save {}: {e:?}", key.as_str());
        }
    }
}
