//! Wi-Fi station: the radio is only brought up the first time it's needed.

use alloc::string::String;
use alloc::vec::Vec;

use embassy_executor::Spawner;
use embassy_net::{Runner, Stack, StackResources};
use esp_hal::peripherals::{FLASH, WIFI};
use esp_nvs::error::Error as NvsError;
use esp_nvs::{Key, Nvs};
use esp_radio::wifi::{
    AuthenticationMethod, Config, Interface, WifiController, scan::ScanConfig, sta::StationConfig,
};
use esp_storage::FlashStorage;
use log::{info, warn};
use static_cell::StaticCell;

/// Offset and size of the "nvs" partition in the default partition table
/// generated by `esp-bootloader-esp-idf` (confirmed at every boot: `nvs
/// WiFi data 01 02 00009000 00006000`). Update these if a custom partition
/// table changes them.
const NVS_PARTITION_OFFSET: usize = 0x9000;
const NVS_PARTITION_SIZE: usize = 0x6000;

const NAMESPACE: Key = Key::from_str("wifi");
const KEY_SSID: Key = Key::from_str("ssid");
const KEY_PASSWORD: Key = Key::from_str("password");

/// An access point found by [`WifiManager::scan`].
pub struct Network {
    pub ssid: String,
    pub signal_strength: i8,
    pub secured: bool,
}

struct Radio {
    controller: WifiController<'static>,
    stack: Stack<'static>,
}

pub struct WifiManager {
    peripheral: Option<WIFI<'static>>,
    spawner: Spawner,
    radio: Option<Radio>,
    /// Strongest BSSID seen per SSID in the last [`Self::scan`], so
    /// [`Self::connect`] can pin to that specific access point instead of
    /// letting the radio associate with any AP sharing the same SSID (common
    /// with mesh/multi-AP setups repeating one network per floor).
    strongest_bssid: Vec<(String, [u8; 6])>,
    /// `None` if the NVS partition couldn't be opened (logged when that
    /// happens); credentials then simply aren't persisted.
    nvs: Option<Nvs<FlashStorage<'static>>>,
}

impl WifiManager {
    pub fn new(peripheral: WIFI<'static>, flash: FLASH<'static>, spawner: Spawner) -> Self {
        let nvs = match Nvs::new(NVS_PARTITION_OFFSET, NVS_PARTITION_SIZE, FlashStorage::new(flash)) {
            Ok(nvs) => Some(nvs),
            Err(e) => {
                warn!("NVS unavailable, Wi-Fi credentials won't persist across reboots: {e:?}");
                None
            }
        };
        Self {
            peripheral: Some(peripheral),
            spawner,
            radio: None,
            strongest_bssid: Vec::new(),
            nvs,
        }
    }

    /// Loads previously saved credentials, if any and readable.
    fn load_saved(&mut self) -> Option<(String, String)> {
        let nvs = self.nvs.as_mut()?;
        let ssid: String = match nvs.get(&NAMESPACE, &KEY_SSID) {
            Ok(ssid) => ssid,
            Err(NvsError::NamespaceNotFound | NvsError::KeyNotFound) => return None,
            Err(e) => {
                warn!("Failed to read saved SSID: {e:?}");
                return None;
            }
        };
        let password: String = match nvs.get(&NAMESPACE, &KEY_PASSWORD) {
            Ok(password) => password,
            Err(e) => {
                warn!("Failed to read saved password: {e:?}");
                return None;
            }
        };
        Some((ssid, password))
    }

    fn save(&mut self, ssid: &str, password: &str) {
        let Some(nvs) = self.nvs.as_mut() else {
            return;
        };
        if let Err(e) = nvs.set(&NAMESPACE, &KEY_SSID, ssid) {
            warn!("Failed to save SSID: {e:?}");
        }
        if let Err(e) = nvs.set(&NAMESPACE, &KEY_PASSWORD, password) {
            warn!("Failed to save password: {e:?}");
        }
    }

    /// Reconnects using previously saved credentials, if any. Meant to be
    /// called once at boot, before serving Improv, so a reboot (losing the
    /// RAM-only radio state) recovers on its own instead of sitting
    /// unprovisioned until the browser reconnects.
    pub async fn reconnect_saved(&mut self) -> bool {
        let Some((ssid, password)) = self.load_saved() else {
            return false;
        };
        info!("Wi-Fi: reconnecting to saved SSID={ssid}");
        self.connect(&ssid, password).await
    }

    /// Connects with newly-provided credentials and, on success, saves them
    /// so [`Self::reconnect_saved`] can use them after a reboot.
    pub async fn provision(&mut self, ssid: &str, password: String) -> bool {
        if self.connect(ssid, password.clone()).await {
            self.save(ssid, &password);
            true
        } else {
            false
        }
    }

    /// Starts the radio in station mode on first use, so that it can scan.
    /// Failures are logged and return `None` rather than panicking, which
    /// would halt the chip and take provisioning down with it.
    fn radio(&mut self) -> Option<&mut Radio> {
        if self.radio.is_none() {
            let (mut controller, interfaces) =
                match esp_radio::wifi::new(self.peripheral.take()?, Default::default()) {
                    Ok(parts) => parts,
                    Err(e) => {
                        warn!("Wi-Fi init failed: {e:?}");
                        return None;
                    }
                };
            if let Err(e) = controller.set_config(&Config::Station(StationConfig::default())) {
                warn!("Wi-Fi start failed: {e:?}");
                return None;
            }

            static RESOURCES: StaticCell<StackResources<3>> = StaticCell::new();
            let seed = esp_hal::time::Instant::now().duration_since_epoch().as_micros() as u64;
            let (stack, runner) = embassy_net::new(
                interfaces.station,
                embassy_net::Config::dhcpv4(Default::default()),
                RESOURCES.init(StackResources::new()),
                seed,
            );
            self.spawner.spawn(net_task(runner).unwrap());

            self.radio = Some(Radio { controller, stack });
        }
        self.radio.as_mut()
    }

    /// Scans for networks, one entry per SSID (the strongest signal, when
    /// several access points share an SSID -- common with mesh/multi-AP
    /// setups repeating one network per floor). Empty if the radio is
    /// unavailable or the scan failed.
    pub async fn scan(&mut self) -> Vec<Network> {
        let Some(radio) = self.radio() else {
            return Vec::new();
        };
        let access_points = match radio
            .controller
            .scan_async(&ScanConfig::default().with_max(20))
            .await
        {
            Ok(access_points) => access_points,
            Err(e) => {
                warn!("Wi-Fi scan failed: {e:?}");
                return Vec::new();
            }
        };

        // One entry per SSID, keeping whichever access point has the best
        // signal; this also becomes `strongest_bssid`, so `connect` can pin
        // to that specific access point instead of letting the radio
        // associate with any AP sharing the same SSID.
        let mut strongest: Vec<(String, [u8; 6], i8, bool)> = Vec::new();
        for ap in &access_points {
            let ssid = ap.ssid.as_str();
            if ssid.is_empty() {
                continue;
            }
            let secured = !matches!(ap.auth_method, None | Some(AuthenticationMethod::None));
            match strongest.iter_mut().find(|(known_ssid, ..)| known_ssid == ssid) {
                Some((_, _, signal_strength, _)) if *signal_strength >= ap.signal_strength => {}
                Some(entry) => *entry = (String::from(ssid), ap.bssid, ap.signal_strength, secured),
                None => strongest.push((String::from(ssid), ap.bssid, ap.signal_strength, secured)),
            }
        }

        self.strongest_bssid = strongest
            .iter()
            .map(|(ssid, bssid, ..)| (ssid.clone(), *bssid))
            .collect();

        strongest
            .into_iter()
            .map(|(ssid, _, signal_strength, secured)| Network {
                ssid,
                signal_strength,
                secured,
            })
            .collect()
    }

    /// Connects and waits for DHCP. `false` if the radio is unavailable or
    /// the access point refused us. Pins to the strongest BSSID seen for
    /// this SSID in the last [`Self::scan`], if any. Doesn't persist
    /// credentials -- see [`Self::provision`] and [`Self::reconnect_saved`].
    async fn connect(&mut self, ssid: &str, password: String) -> bool {
        let bssid = self
            .strongest_bssid
            .iter()
            .find(|(known_ssid, _)| known_ssid == ssid)
            .map(|(_, bssid)| *bssid);
        if bssid.is_none() {
            warn!("Wi-Fi: no scan result for {ssid}, letting the radio pick an access point");
        }

        let Some(radio) = self.radio() else {
            return false;
        };
        let mut config = StationConfig::default()
            .with_ssid(ssid)
            .with_password(password);
        if let Some(bssid) = bssid {
            config = config.with_bssid(bssid);
        }
        let config = Config::Station(config);
        if radio.controller.set_config(&config).is_err()
            || radio.controller.connect_async().await.is_err()
        {
            warn!("Wi-Fi: connection to {ssid} failed");
            return false;
        }

        radio.stack.wait_config_up().await;
        info!("Wi-Fi connected, ip = {:?}", radio.stack.config_v4());
        true
    }

    pub fn is_online(&self) -> bool {
        self.radio
            .as_ref()
            .is_some_and(|radio| radio.stack.config_v4().is_some())
    }
}

#[embassy_executor::task]
async fn net_task(mut runner: Runner<'static, Interface<'static>>) -> ! {
    runner.run().await
}
